package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// ReportInfo holds the context needed to generate a backup report
type ReportInfo struct {
	Operation       string // "backup", "force-backup", "remote-backup", "push-backup"
	SourcePool      string
	DestPool        string
	RemoteHost      string // For remote operations
	StartTime       time.Time
	EndTime         time.Time
	DatasetProgress []DatasetProgress
	Success         bool
	ErrorMessage    string
	OperationLog    string // The raw output from the backup operation
}

// getRealUserHome returns the home directory of the real user, even when running
// under sudo. Falls back to os.UserHomeDir if SUDO_USER is not set.
func getRealUserHome() (string, error) {
	// When running under sudo, use the real user's home
	if sudoUser := os.Getenv("SUDO_USER"); sudoUser != "" {
		home := filepath.Join("/home", sudoUser)
		if _, err := os.Stat(home); err == nil {
			return home, nil
		}
	}
	return os.UserHomeDir()
}

// getReportsDir returns the reports directory, creating it if needed.
// Uses the real user's home directory even when running under sudo.
func getReportsDir() (string, error) {
	home, err := getRealUserHome()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(home, ".local", "share", "zfs-backup", "reports")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	// If running as sudo, fix ownership so the real user can access the files
	if sudoUser := os.Getenv("SUDO_USER"); sudoUser != "" {
		_ = exec.Command("chown", "-R", sudoUser+":"+sudoUser, filepath.Join(home, ".local", "share", "zfs-backup")).Run()
	}
	return dir, nil
}

// generateReportFilename creates a descriptive filename for the report
// e.g. Backup-NIXROOT-to-NIXBACKUPS-18May2026-10h00-Report
func generateReportFilename(info ReportInfo) string {
	prefix := "Backup"
	switch info.Operation {
	case "force-backup":
		prefix = "ForceBackup"
	case "remote-backup":
		prefix = "PullBackup"
	case "push-backup":
		prefix = "PushBackup"
	case "prepare":
		prefix = "Prepare"
	case "unmount":
		prefix = "Unmount"
	case "recover":
		prefix = "Recover"
	}

	src := info.SourcePool
	dst := info.DestPool
	if info.RemoteHost != "" {
		host := info.RemoteHost
		if parts := strings.Split(host, "@"); len(parts) > 1 {
			host = parts[1]
		}
		if info.Operation == "push-backup" {
			dst = host
		} else {
			src = host
		}
	}
	if src == "" {
		src = "local"
	}
	if dst == "" {
		dst = "local"
	}

	ts := info.StartTime.Format("02Jan2006-15h04")
	return fmt.Sprintf("%s-%s-to-%s-%s-Report", prefix, src, dst, ts)
}

// generateMarkdownReport creates a comprehensive, branded markdown report
func generateMarkdownReport(info ReportInfo) string {
	var b strings.Builder
	totalDuration := info.EndTime.Sub(info.StartTime)

	// Header with Kartoza branding
	b.WriteString("# Kartoza ZFS Backup Report\n\n")
	b.WriteString(fmt.Sprintf("> Generated by **%s** v%s\n", appName, appVersion))
	b.WriteString(fmt.Sprintf("> %s\n\n", info.StartTime.Format("Monday, 02 January 2006 at 15:04")))

	// Result banner
	if info.Success {
		b.WriteString("**Result: BACKUP COMPLETED SUCCESSFULLY**\n\n")
	} else {
		b.WriteString("**Result: BACKUP FAILED**\n\n")
	}

	// What happened - plain language overview
	b.WriteString("## What happened\n\n")
	b.WriteString(writeNarrativeSummary(info, totalDuration))
	b.WriteString("\n")

	// Technical summary table
	b.WriteString("## Technical Summary\n\n")
	b.WriteString("| | |\n")
	b.WriteString("|---|---|\n")
	b.WriteString(fmt.Sprintf("| **Operation** | %s |\n", operationLabel(info.Operation)))
	b.WriteString(fmt.Sprintf("| **Source** | `%s` |\n", info.SourcePool))
	b.WriteString(fmt.Sprintf("| **Destination** | `%s` |\n", info.DestPool))
	if info.RemoteHost != "" {
		b.WriteString(fmt.Sprintf("| **Remote Host** | `%s` |\n", info.RemoteHost))
	}
	b.WriteString(fmt.Sprintf("| **Started** | %s |\n", info.StartTime.Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("| **Finished** | %s |\n", info.EndTime.Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("| **Total Duration** | %s |\n", formatDuration(totalDuration)))
	b.WriteString("\n")

	// Dataset sync results
	if len(info.DatasetProgress) > 0 {
		doneCount := 0
		errorCount := 0
		skippedCount := 0
		totalSnapshots := 0
		var totalSyncTime time.Duration
		for _, ds := range info.DatasetProgress {
			totalSyncTime += ds.Duration
			totalSnapshots += len(ds.Snapshots)
			switch ds.Status {
			case DatasetDone:
				doneCount++
			case DatasetError:
				errorCount++
			case DatasetSkipped:
				skippedCount++
			}
		}

		b.WriteString("## Dataset Sync Results\n\n")
		b.WriteString(fmt.Sprintf("A total of **%d dataset(s)** were processed ", len(info.DatasetProgress)))
		b.WriteString(fmt.Sprintf("containing **%d snapshots** across all datasets. ", totalSnapshots))
		b.WriteString(fmt.Sprintf("The sync phase took **%s** of wall-clock time.\n\n", formatDuration(totalSyncTime)))

		if errorCount > 0 || skippedCount > 0 {
			b.WriteString(fmt.Sprintf("- **%d** synced successfully\n", doneCount))
			if errorCount > 0 {
				b.WriteString(fmt.Sprintf("- **%d** failed with errors (see details below)\n", errorCount))
			}
			if skippedCount > 0 {
				b.WriteString(fmt.Sprintf("- **%d** skipped (destination could not be prepared)\n", skippedCount))
			}
			b.WriteString("\n")
		}

		// Dataset detail table
		b.WriteString("| Dataset | Size | Snapshots | Sync Time | Status |\n")
		b.WriteString("|---------|------|-----------|-----------|--------|\n")
		for _, ds := range info.DatasetProgress {
			status := datasetStatusLabel(ds.Status)
			size := ds.Size
			if size == "" || size == "?" {
				size = "-"
			}
			dur := "-"
			if ds.Duration > 0 {
				dur = formatDuration(ds.Duration)
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | %d | %s | %s |\n",
				ds.Name, size, len(ds.Snapshots), dur, status))
		}
		b.WriteString("\n")

		// Pool tree view: pool > datasets > snapshots with check/cross marks
		b.WriteString("## Backup Tree\n\n")
		b.WriteString("This tree shows exactly what was backed up. Each snapshot is marked:\n")
		b.WriteString("- ✓ synced successfully to the backup destination\n")
		b.WriteString("- ✕ failed to sync\n")
		b.WriteString("- ○ not transferred\n\n")

		b.WriteString("```\n")
		poolName := info.SourcePool
		if poolName == "" {
			poolName = "pool"
		}

		// Pool root
		poolStatus := "✓"
		if !info.Success {
			poolStatus = "✕"
		}
		b.WriteString(fmt.Sprintf("%s %s\n", poolStatus, poolName))

		for di, ds := range info.DatasetProgress {
			isLastDS := di == len(info.DatasetProgress)-1
			branch := "├── "
			childPrefix := "│   "
			if isLastDS {
				branch = "└── "
				childPrefix = "    "
			}

			// Dataset line with status, name, size, time
			dsIcon := "✓"
			switch ds.Status {
			case DatasetError:
				dsIcon = "✕"
			case DatasetSkipped:
				dsIcon = "○"
			case DatasetPending:
				dsIcon = "○"
			}

			dsLine := fmt.Sprintf("%s%s %s", branch, dsIcon, ds.Name)
			if ds.Size != "" && ds.Size != "?" {
				dsLine += fmt.Sprintf("  [%s]", ds.Size)
			}
			if ds.Duration > 0 {
				dsLine += fmt.Sprintf("  %s", formatDuration(ds.Duration))
			}
			b.WriteString(dsLine + "\n")

			// Snapshot children
			for si, snap := range ds.Snapshots {
				isLastSnap := si == len(ds.Snapshots)-1
				snapBranch := childPrefix + "├── "
				if isLastSnap {
					snapBranch = childPrefix + "└── "
				}

				snapIcon := "✓"
				switch snap.Status {
				case SnapError:
					snapIcon = "✕"
				case SnapPending:
					snapIcon = "○"
				}

				snapLine := fmt.Sprintf("%s%s @%s", snapBranch, snapIcon, snap.Tag)
				if snap.Size != "" && snap.Size != "0" && snap.Size != "0B" {
					snapLine += fmt.Sprintf("  (%s)", snap.Size)
				}
				b.WriteString(snapLine + "\n")
			}
		}
		b.WriteString("```\n\n")

		// Errors section
		hasErrors := false
		for _, ds := range info.DatasetProgress {
			if ds.ErrorMsg != "" {
				hasErrors = true
				break
			}
		}
		if hasErrors {
			b.WriteString("## Errors\n\n")
			b.WriteString("The following datasets encountered problems during sync. ")
			b.WriteString("These errors do not necessarily mean data was lost - the backup ")
			b.WriteString("tool will retry failed datasets on the next run.\n\n")
			for _, ds := range info.DatasetProgress {
				if ds.ErrorMsg != "" {
					b.WriteString(fmt.Sprintf("### `%s`\n\n", ds.Name))
					b.WriteString(fmt.Sprintf("**Status:** %s\n\n", datasetStatusLabel(ds.Status)))
					b.WriteString(fmt.Sprintf("```\n%s\n```\n\n", ds.ErrorMsg))
				}
			}
		}
	} else if info.ErrorMessage != "" {
		// No dataset progress but there was an error
		b.WriteString("## Error Details\n\n")
		b.WriteString(fmt.Sprintf("```\n%s\n```\n\n", info.ErrorMessage))
	}

	// Operation log
	if info.OperationLog != "" {
		b.WriteString("## Operation Log\n\n")
		b.WriteString("Full output from the backup process:\n\n")
		b.WriteString("<details><summary>Click to expand</summary>\n\n")
		b.WriteString("```\n")
		b.WriteString(info.OperationLog)
		b.WriteString("\n```\n\n")
		b.WriteString("</details>\n\n")
	}

	// What to do next
	b.WriteString("## What to do next\n\n")
	if info.Success {
		b.WriteString("Your data is safely backed up. No action is required.\n\n")
		b.WriteString("- To verify the backup, use **Show zpool info** in the application\n")
		b.WriteString("- To safely disconnect the backup drive, use **Unmount Backup Disk**\n")
		b.WriteString("- Previous reports are stored in `~/.local/share/zfs-backup/reports/`\n")
	} else {
		b.WriteString("The backup did not complete successfully. Here are some things to try:\n\n")
		b.WriteString("1. **Run the backup again** - transient errors often resolve on retry\n")
		b.WriteString("2. **Use Recover Failed Backup** to clear stale receive state\n")
		b.WriteString("3. **Check disk health** with Pool Maintenance > Scrub\n")
		b.WriteString("4. **Use Force Backup** as a last resort to reset the sync chain\n")
	}
	b.WriteString("\n")

	// Footer
	b.WriteString("---\n\n")
	b.WriteString(fmt.Sprintf("*%s v%s* | ", appName, appVersion))
	b.WriteString(fmt.Sprintf("Made with <3 by [Kartoza](%s) | ", kartozaURL))
	b.WriteString(fmt.Sprintf("[Donate](%s) | ", donateURL))
	b.WriteString(fmt.Sprintf("[GitHub](%s)\n", githubURL))

	return b.String()
}

// writeNarrativeSummary creates a plain-language description of what happened
func writeNarrativeSummary(info ReportInfo, totalDuration time.Duration) string {
	var b strings.Builder

	switch info.Operation {
	case "backup":
		b.WriteString(fmt.Sprintf("An **incremental backup** was performed from the local ZFS pool "+
			"`%s` to the backup pool `%s`. ", info.SourcePool, info.DestPool))
		b.WriteString("Incremental backups use ZFS send/receive to transfer only the data that "+
			"has changed since the last backup, making them fast and space-efficient. ")
		b.WriteString("The tool creates a point-in-time snapshot, syncs each dataset using syncoid, "+
			"then prunes old snapshots to save space.\n\n")
	case "force-backup":
		b.WriteString(fmt.Sprintf("A **force backup** was performed from `%s` to `%s`. ", info.SourcePool, info.DestPool))
		b.WriteString("This is a destructive operation that resets the backup chain. Old snapshots "+
			"on the destination were deleted and a full resync was performed. This is typically "+
			"used when the incremental chain is broken or corrupted.\n\n")
	case "remote-backup":
		b.WriteString(fmt.Sprintf("A **remote pull backup** was performed, pulling data from `%s` on "+
			"remote host `%s` to the local backup pool `%s`. ", info.SourcePool, info.RemoteHost, info.DestPool))
		b.WriteString("Data was transferred over SSH using syncoid, which efficiently sends only "+
			"the changes since the last backup.\n\n")
	case "push-backup":
		b.WriteString(fmt.Sprintf("A **push backup** was performed, pushing data from the local pool "+
			"`%s` to the remote backup server `%s` (pool `%s`). ", info.SourcePool, info.RemoteHost, info.DestPool))
		b.WriteString("Data was transferred over SSH using syncoid.\n\n")
	case "prepare":
		b.WriteString(fmt.Sprintf("A new backup device was **prepared** as an encrypted ZFS pool `%s`. ", info.DestPool))
		b.WriteString("The device was wiped, a GPT partition table was created, and an AES-256-GCM "+
			"encrypted ZFS pool was set up with zstd compression.\n\n")
	case "unmount":
		b.WriteString(fmt.Sprintf("The backup pool `%s` was **safely unmounted** and the USB drive "+
			"was powered off. ", info.DestPool))
		b.WriteString("It is now safe to physically disconnect the drive.\n\n")
	case "recover":
		b.WriteString(fmt.Sprintf("A **recovery operation** was performed on the backup pool `%s`. ", info.DestPool))
		b.WriteString("This clears any partial receive state left by an interrupted backup and "+
			"analyses the snapshot chain to determine if incremental sync is still possible.\n\n")
	default:
		b.WriteString(fmt.Sprintf("A `%s` operation was performed. ", info.Operation))
	}

	if len(info.DatasetProgress) > 0 {
		doneCount := 0
		errorCount := 0
		for _, ds := range info.DatasetProgress {
			switch ds.Status {
			case DatasetDone:
				doneCount++
			case DatasetError, DatasetSkipped:
				errorCount++
			}
		}
		b.WriteString(fmt.Sprintf("**%d dataset(s)** were processed. ", len(info.DatasetProgress)))
		if errorCount == 0 {
			b.WriteString(fmt.Sprintf("All %d completed successfully. ", doneCount))
		} else {
			b.WriteString(fmt.Sprintf("%d completed successfully and %d had errors. ", doneCount, errorCount))
		}
	}

	b.WriteString(fmt.Sprintf("The operation took **%s** in total.", formatDuration(totalDuration)))

	if !info.Success && info.ErrorMessage != "" {
		b.WriteString(fmt.Sprintf("\n\n**The operation failed:** %s", info.ErrorMessage))
	}

	b.WriteString("\n")
	return b.String()
}

// writeBackupReport writes the report as markdown and attempts PDF conversion.
// Returns the paths to the generated files and any error.
func writeBackupReport(info ReportInfo) (mdPath, pdfPath string, err error) {
	dir, err := getReportsDir()
	if err != nil {
		return "", "", fmt.Errorf("failed to create reports directory: %w", err)
	}

	baseName := generateReportFilename(info)
	mdPath = filepath.Join(dir, baseName+".md")
	pdfPath = filepath.Join(dir, baseName+".pdf")

	markdown := generateMarkdownReport(info)

	if err := os.WriteFile(mdPath, []byte(markdown), 0644); err != nil {
		return "", "", fmt.Errorf("failed to write markdown report: %w", err)
	}

	pdfErr := generatePDF(info, pdfPath)
	if pdfErr != nil {
		pdfPath = ""
	}

	// Fix file ownership when running under sudo so the real user can access them
	chownToRealUser(mdPath)
	if pdfPath != "" {
		chownToRealUser(pdfPath)
	}

	return mdPath, pdfPath, nil
}

// chownToRealUser changes file ownership to the real user when running under sudo
func chownToRealUser(path string) {
	if sudoUser := os.Getenv("SUDO_USER"); sudoUser != "" {
		_ = exec.Command("chown", sudoUser+":"+sudoUser, path).Run()
	}
}

// openFileForUser opens a file or URL using xdg-open, running as the real user
// if under sudo. Preserves display environment variables so the user's desktop
// session can open the file.
func openFileForUser(path string) error {
	if sudoUser := os.Getenv("SUDO_USER"); sudoUser != "" {
		// Build a command that preserves the display environment
		// so xdg-open can reach the user's desktop session
		envVars := []string{"DISPLAY", "WAYLAND_DISPLAY", "XDG_RUNTIME_DIR", "DBUS_SESSION_BUS_ADDRESS"}
		var envPrefix string
		for _, v := range envVars {
			if val := os.Getenv(v); val != "" {
				envPrefix += v + "=" + val + " "
			}
		}
		shell := fmt.Sprintf("%sxdg-open %q", envPrefix, path)
		return exec.Command("sudo", "-u", sudoUser, "bash", "-c", shell).Start()
	}
	return exec.Command("xdg-open", path).Start()
}

// generatePDF creates a PDF report using the go-pdf/fpdf library (no external deps).
func generatePDF(info ReportInfo, pdfPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	// Kartoza brand colors
	gold := [3]int{223, 158, 47}    // #DF9E2F
	blue := [3]int{86, 159, 198}    // #569FC6
	teal := [3]int{6, 150, 154}     // #06969A
	gray := [3]int{138, 139, 139}   // #8A8B8B
	red := [3]int{204, 4, 3}        // #CC0403
	dark := [3]int{30, 30, 30}      // #1E1E1E

	totalDuration := info.EndTime.Sub(info.StartTime)

	// Header bar
	pdf.SetFillColor(dark[0], dark[1], dark[2])
	pdf.Rect(0, 0, 210, 28, "F")
	pdf.SetTextColor(gold[0], gold[1], gold[2])
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetXY(15, 8)
	pdf.CellFormat(0, 10, "Kartoza ZFS Backup Report", "", 1, "L", false, 0, "")
	pdf.SetTextColor(blue[0], blue[1], blue[2])
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(15, 18)
	pdf.CellFormat(0, 5, fmt.Sprintf("%s v%s  |  %s",
		appName, appVersion, info.StartTime.Format("Monday, 02 January 2006 at 15:04")), "", 1, "L", false, 0, "")

	pdf.Ln(10)

	// Result banner
	pdf.SetFont("Helvetica", "B", 14)
	if info.Success {
		pdf.SetTextColor(teal[0], teal[1], teal[2])
		pdf.CellFormat(0, 10, "BACKUP COMPLETED SUCCESSFULLY", "", 1, "L", false, 0, "")
	} else {
		pdf.SetTextColor(red[0], red[1], red[2])
		pdf.CellFormat(0, 10, "BACKUP FAILED", "", 1, "L", false, 0, "")
	}
	pdf.Ln(3)

	// Summary section
	pdf.SetTextColor(dark[0], dark[1], dark[2])
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Summary", "", 1, "L", false, 0, "")
	pdf.SetDrawColor(gray[0], gray[1], gray[2])
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(2)

	pdfKeyValue(pdf, dark, gray, "Operation", operationLabel(info.Operation))
	pdfKeyValue(pdf, dark, gray, "Source", info.SourcePool)
	pdfKeyValue(pdf, dark, gray, "Destination", info.DestPool)
	if info.RemoteHost != "" {
		pdfKeyValue(pdf, dark, gray, "Remote Host", info.RemoteHost)
	}
	pdfKeyValue(pdf, dark, gray, "Started", info.StartTime.Format("2006-01-02 15:04:05"))
	pdfKeyValue(pdf, dark, gray, "Finished", info.EndTime.Format("2006-01-02 15:04:05"))
	pdfKeyValue(pdf, dark, gray, "Duration", formatDuration(totalDuration))
	pdf.Ln(5)

	// Dataset results
	if len(info.DatasetProgress) > 0 {
		doneCount := 0
		errorCount := 0
		totalSnapshots := 0
		var totalSyncTime time.Duration
		for _, ds := range info.DatasetProgress {
			totalSyncTime += ds.Duration
			totalSnapshots += len(ds.Snapshots)
			switch ds.Status {
			case DatasetDone:
				doneCount++
			case DatasetError, DatasetSkipped:
				errorCount++
			}
		}

		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetTextColor(dark[0], dark[1], dark[2])
		pdf.CellFormat(0, 8, "Dataset Sync Results", "", 1, "L", false, 0, "")
		pdf.SetDrawColor(gray[0], gray[1], gray[2])
		pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
		pdf.Ln(2)

		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(gray[0], gray[1], gray[2])
		pdf.CellFormat(0, 5, fmt.Sprintf("%d dataset(s)  |  %d synced  |  %d failed  |  %d snapshots  |  %s total sync time",
			len(info.DatasetProgress), doneCount, errorCount, totalSnapshots, formatDuration(totalSyncTime)), "", 1, "L", false, 0, "")
		pdf.Ln(3)

		// Dataset table
		colWidths := []float64{40, 20, 22, 25, 18}
		headers := []string{"Dataset", "Size", "Snapshots", "Sync Time", "Status"}

		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(dark[0], dark[1], dark[2])
		pdf.SetTextColor(255, 255, 255)
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 6, h, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Helvetica", "", 8)
		for _, ds := range info.DatasetProgress {
			// Row color based on status
			switch ds.Status {
			case DatasetDone:
				pdf.SetTextColor(dark[0], dark[1], dark[2])
			case DatasetError:
				pdf.SetTextColor(red[0], red[1], red[2])
			case DatasetSkipped:
				pdf.SetTextColor(gray[0], gray[1], gray[2])
			default:
				pdf.SetTextColor(dark[0], dark[1], dark[2])
			}

			size := ds.Size
			if size == "" || size == "?" {
				size = "-"
			}
			dur := "-"
			if ds.Duration > 0 {
				dur = formatDuration(ds.Duration)
			}

			pdf.CellFormat(colWidths[0], 5, ds.Name, "1", 0, "L", false, 0, "")
			pdf.CellFormat(colWidths[1], 5, size, "1", 0, "R", false, 0, "")
			pdf.CellFormat(colWidths[2], 5, fmt.Sprintf("%d", len(ds.Snapshots)), "1", 0, "C", false, 0, "")
			pdf.CellFormat(colWidths[3], 5, dur, "1", 0, "R", false, 0, "")
			pdf.CellFormat(colWidths[4], 5, datasetStatusLabel(ds.Status), "1", 0, "C", false, 0, "")
			pdf.Ln(-1)
		}
		pdf.Ln(5)

		// Backup tree
		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetTextColor(dark[0], dark[1], dark[2])
		pdf.CellFormat(0, 8, "Backup Tree", "", 1, "L", false, 0, "")
		pdf.SetDrawColor(gray[0], gray[1], gray[2])
		pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
		pdf.Ln(2)

		pdf.SetFont("Courier", "", 7)
		poolIcon := "+"
		if !info.Success {
			poolIcon = "x"
		}
		poolName := info.SourcePool
		if poolName == "" {
			poolName = "pool"
		}
		pdfTreeLine(pdf, dark, teal, red, gray, 0, poolIcon, poolName, "", "")

		for di, ds := range info.DatasetProgress {
			isLastDS := di == len(info.DatasetProgress)-1
			dsIcon := "+"
			dsColor := teal
			switch ds.Status {
			case DatasetError:
				dsIcon = "x"
				dsColor = red
			case DatasetSkipped, DatasetPending:
				dsIcon = "o"
				dsColor = gray
			}

			sizeStr := ""
			if ds.Size != "" && ds.Size != "?" {
				sizeStr = ds.Size
			}
			durStr := ""
			if ds.Duration > 0 {
				durStr = formatDuration(ds.Duration)
			}
			indent := 1
			branch := "|--"
			if isLastDS {
				branch = "\\--"
			}
			_ = dsColor
			pdfTreeLineWithBranch(pdf, dark, dsColor, red, gray, indent, branch, dsIcon, ds.Name, sizeStr, durStr)

			for si, snap := range ds.Snapshots {
				isLastSnap := si == len(ds.Snapshots)-1
				snapIcon := "+"
				snapColor := blue
				switch snap.Status {
				case SnapError:
					snapIcon = "x"
					snapColor = red
				case SnapPending:
					snapIcon = "o"
					snapColor = gray
				}
				_ = snapColor

				childPrefix := "|   "
				if isLastDS {
					childPrefix = "    "
				}
				snapBranch := childPrefix + "|--"
				if isLastSnap {
					snapBranch = childPrefix + "\\--"
				}
				snapSize := ""
				if snap.Size != "" && snap.Size != "0" && snap.Size != "0B" {
					snapSize = snap.Size
				}
				pdfTreeLineWithBranch(pdf, dark, snapColor, red, gray, indent+1, snapBranch, snapIcon, "@"+snap.Tag, snapSize, "")
			}
		}
		pdf.Ln(5)

		// Errors section
		hasErrors := false
		for _, ds := range info.DatasetProgress {
			if ds.ErrorMsg != "" {
				hasErrors = true
				break
			}
		}
		if hasErrors {
			pdf.SetFont("Helvetica", "B", 12)
			pdf.SetTextColor(red[0], red[1], red[2])
			pdf.CellFormat(0, 8, "Errors", "", 1, "L", false, 0, "")
			pdf.SetDrawColor(red[0], red[1], red[2])
			pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
			pdf.Ln(2)

			pdf.SetFont("Helvetica", "", 8)
			for _, ds := range info.DatasetProgress {
				if ds.ErrorMsg != "" {
					pdf.SetTextColor(dark[0], dark[1], dark[2])
					pdf.SetFont("Helvetica", "B", 8)
					pdf.CellFormat(0, 5, ds.Name, "", 1, "L", false, 0, "")
					pdf.SetFont("Helvetica", "", 7)
					pdf.SetTextColor(red[0], red[1], red[2])
					pdf.MultiCell(0, 4, ds.ErrorMsg, "", "L", false)
					pdf.Ln(2)
				}
			}
		}
	}

	// Footer
	pdf.Ln(5)
	pdf.SetDrawColor(gray[0], gray[1], gray[2])
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(gray[0], gray[1], gray[2])
	pdf.CellFormat(0, 4, fmt.Sprintf("%s v%s  |  Made with love by Kartoza  |  %s", appName, appVersion, kartozaURL), "", 1, "C", false, 0, "")

	return pdf.OutputFileAndClose(pdfPath)
}

// pdfKeyValue renders a key-value pair in the PDF
func pdfKeyValue(pdf *fpdf.Fpdf, dark, labelColor [3]int, key, value string) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(labelColor[0], labelColor[1], labelColor[2])
	pdf.CellFormat(35, 5, key, "", 0, "R", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(dark[0], dark[1], dark[2])
	pdf.CellFormat(0, 5, "  "+value, "", 1, "L", false, 0, "")
}

// pdfTreeLine renders a root-level tree line
func pdfTreeLine(pdf *fpdf.Fpdf, dark, okColor, errColor, dimColor [3]int, indent int, icon, name, size, dur string) {
	pdfTreeLineWithBranch(pdf, dark, okColor, errColor, dimColor, indent, "", icon, name, size, dur)
}

// pdfTreeLineWithBranch renders a tree line with a branch prefix
func pdfTreeLineWithBranch(pdf *fpdf.Fpdf, dark, okColor, errColor, dimColor [3]int, indent int, branch, icon, name, size, dur string) {
	pdf.SetFont("Courier", "", 7)
	line := branch
	switch icon {
	case "+":
		line += " [+] "
		pdf.SetTextColor(okColor[0], okColor[1], okColor[2])
	case "x":
		line += " [x] "
		pdf.SetTextColor(errColor[0], errColor[1], errColor[2])
	default:
		line += " [o] "
		pdf.SetTextColor(dimColor[0], dimColor[1], dimColor[2])
	}
	line += name
	if size != "" {
		line += "  (" + size + ")"
	}
	if dur != "" {
		line += "  " + dur
	}
	pdf.CellFormat(0, 3.5, line, "", 1, "L", false, 0, "")
}

// operationLabel returns a human-readable label for the operation type
func operationLabel(op string) string {
	switch op {
	case "backup":
		return "Incremental Backup"
	case "force-backup":
		return "Force Backup (destructive)"
	case "remote-backup":
		return "Pull Remote Backup"
	case "push-backup":
		return "Push Backup to Remote"
	case "prepare":
		return "Prepare Backup Device"
	case "unmount":
		return "Unmount Backup Disk"
	case "recover":
		return "Recover Failed Backup"
	default:
		return op
	}
}

// datasetStatusLabel returns a readable status label
func datasetStatusLabel(status DatasetSyncStatus) string {
	switch status {
	case DatasetDone:
		return "OK"
	case DatasetError:
		return "FAILED"
	case DatasetSkipped:
		return "SKIPPED"
	case DatasetPending:
		return "PENDING"
	case DatasetSyncing:
		return "SYNCING"
	default:
		return "UNKNOWN"
	}
}

// datasetStatusBadge returns a markdown-friendly badge for the status
func datasetStatusBadge(status DatasetSyncStatus) string {
	switch status {
	case DatasetDone:
		return "**[OK]**"
	case DatasetError:
		return "**[FAIL]**"
	case DatasetSkipped:
		return "**[SKIP]**"
	default:
		return "[-]"
	}
}
